language: python

matrix:
    include:
        - os: linux
          python: 3.6


services:
  - docker


before_install:
  - docker build -t perspect .
  - docker run -d -p 127.0.0.1:80:4567 testperspect:latest /bin/sh -c "cd /home/fenics/shared;"


install:
  - echo $pwd

script:
  - cd tests
  - pytest .
